config/routes.rb
Zynch::Application.routes.draw do
  devise_for :users
  
  resources :visits
  
  resources :accounts do
    member do
      get 'show_code'
      get 'export'
    end
  end

  get '/zys.js' => 'visits#script', :as => 'zys', :format => :js
  get '/zyt.js' => 'visits#track', :as => 'zyt', :format => :js
  
  root :to => 'accounts#index'
  

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :visits, :dependent => :destroy
  has_many :pages, :dependent => :destroy
  
  validates :name, :presence => true
  validates :domain, :presence => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, :presence => true
  
  def code
    "ZY-#{'%010d' % self.id}"
  end
  
  def track(params)
    path = ::Param::parse(params[:pn], :to_s)
    page = nil
    unless path.nil?
      page = self.pages.find_or_create_by_path(path)
      page.host = ::Param::parse(params[:hn], :to_s)
      page.search = ::Param::parse(params[:ss], :to_s)
      page.charset = ::Param::parse(params[:cs], :to_s)
      page.title = ::Param::parse(params[:pt], :to_s)
      page.save
    end
    
    visit = self.visits.find_by_id ::Param::parse(params[:id], :to_i)
    new_session = false
    if visit.nil? # new session
      new_session = true
      visit = self.visits.build
      visit.ip_address = params[:ip]
      visit.update_attributes_from_params(params)
      
      location = ::Geo.resolve(visit.ip_address)
      if !location.nil? and location.country_code
        country = Country.find_or_create_by_id(location.country_code)
        country.name = location.country_name
        country.save
        visit.country = country
      end
    end
      
    visit.entry_page = page if visit.entry_page.nil?
    visit.exit_page = page
    visit.save
    
    pageview = visit.pageviews.build
    pageview.page = page
    pageview.save
    
    [new_session, visit]
  end
  
end

app/controllers/accounts_controller.rb
require 'csv'

class AccountsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_account, :only => [ :show, :export, :show_code, :edit, :update, :destroy ]
  
  def index
    @accounts = current_user.accounts
  end
  
  def show
    pages = %w{ browser os screen_resolution major_flash_version country_id language page }
    @partial = 'by_default'
    
    if @account.visits.count.zero?
      flash[:alert] = 'not enough data to generate report'
      redirect_to :action => 'index'
    else
      if params[:range].blank?
        min_date = @account.visits.minimum('created_at')
        max_date = @account.visits.maximum('created_at')
        params[:range] = [min_date, max_date].map { |d| d.to_date.to_s }.join(",")
      end
      @start_date, @end_date = params[:range].split(',').map { |d| d.to_date }

      params[:by] = nil if params[:by].blank?
      
      s = @account.visits
      s = s.where('created_at BETWEEN ? AND ?', @start_date, @end_date) if @start_date != @end_date
      if pages.include?(params[:by])
        @partial = "by_#{params[:by]}"

        case params[:by]
        when 'page'
          @entry_visits = s.count_by('entry_page_id').order('visits DESC').limit(5)
          @exit_visits = s.count_by('exit_page_id').order('visits DESC').limit(5)
        else
          @visits = s.count_by(params[:by])
        end
      else
        s = s.select('YEAR(created_at) AS year, MONTH(created_at) AS month, DAY(created_at) AS day, COUNT(*) AS visits, SUM(pageviews_count) AS hits')
        @visits = s.group('year, month, day').order('year, month, day')
        @monthly_visits = s.group('year, month').order('year, month')
        @visit_duration = s.select('TIME_TO_SEC(TIMEDIFF(updated_at, created_at)) AS duration').group('year, month').order('year, month')
      end
    end
  end
  
  def export
    respond_to do |format|
      format.csv do 
        @visits = @account.visits.includes([:entry_page, :exit_page])
        csv_string = CSV.generate :col_sep => ';' do |csv|
          csv << ['entry', 'exit', *@visits.first.attributes.map { |k, v| k.to_s }]
          @visits.each do |visit|
            csv << [visit.entry_page.path, visit.exit_page.path, *visit.attributes.map { |k, v| v }]
          end
        end
        filename = @account.name.downcase.gsub(/[^0-9a-z]/, "_") + ".csv"
        send_data(csv_string, :type => 'text/csv; charset=utf-8', :filename => filename)
      end
    end
  end
  
  def show_code
  end
  
  def new
    @account = current_user.accounts.build
  end
  
  def create
    @account = current_user.accounts.build(params[:account])
    if @account.save
      flash[:notice] = "Account successfully created!"
      redirect_to show_code_account_url(@account)
    else
      render :action => 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @account.update_attributes(params[:account])
      flash[:notice] = "Account information successfully updated!"
      redirect_to show_code_account_url(@account)
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @account.destroy
    redirect_to accounts_url
  end
  
private
  def find_account
    @account = current_user.accounts.find(params[:id])
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
  
  def dashboard_menu_item(account, title, by)
    content_tag :li, :class => (params[:by] == by ? 'active' : nil) do 
      link_to title, account_path(account, :by => by, :range => params[:range])
    end
  end
  
end

app/views/accounts/_by_browser.html.erb
<h2>Visits by browser</h2>
<div class="visualization" id='visualization'></div>

<script type='text/javascript'>
  google.load('visualization', '1', { packages:['corechart']});
  google.setOnLoadCallback(drawVisualization);

  function drawVisualization() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Browser');
    data.addColumn('number', 'visits'); 
    <% @visits.each do |visit| %>
      data.addRow(['<%= visit[:browser] %>', <%= visit[:visits] %>]);
    <% end %>

    new google.visualization.PieChart(document.getElementById('visualization')).draw(data);
  }
</script>

app/views/accounts/_by_country_id.html.erb
<h2>Visits by country</h2>
<div class="visualization" id='visualization'></div>

<script type='text/javascript'>
   google.load('visualization', '1', {'packages': ['geomap']});
   google.setOnLoadCallback(drawMap);

    function drawMap() {
      var data = new google.visualization.DataTable();
      data.addRows(6);
      data.addColumn('string', 'Country');
      data.addColumn('number', 'Popularity');
      <% @visits.each do |visit| %>
        data.addRow(['<%= visit[:country_id] %>', <%= visit[:visits] %>]);
      <% end %>

      var options = {};
      options['dataMode'] = 'regions';
      options['width'] = '750px';
      options['height'] = '500px';

      var container = document.getElementById('visualization');
      var geomap = new google.visualization.GeoMap(container);
      geomap.draw(data, options);
  };
  </script>

app/views/accounts/_by_default.html.erb
<h2>Summary of visits and pageviews</h2>
<h3>Visits and pageviews per month</h3>
<div class="visualization" id='by_month'></div>

<h3>Page views per visit</h3>
<div class="visualization" id='pageviews_per_visit'></div>

<h3>Visit dutration by month</h3>
<div class="visualization" id='visit_dutration'></div>

<h3>Visits and pageviews by day</h3>
<div class="visualization" id='overall'></div>




<script type='text/javascript'>
  google.load('visualization', '1', {'packages':['annotatedtimeline', 'corechart']});
  google.setOnLoadCallback(drawVisualization);

  function drawVisualization() {
    var data = new google.visualization.DataTable();
    data.addColumn('date', 'Date');
    data.addColumn('number', 'Visits'); 
    data.addColumn('number', 'Pageviews'); 
    <% @visits.each do |visit| %>
      data.addRow([new Date(<%= visit[:year] %>, <%= visit[:month] %> - 1, <%= visit[:day] %>), <%= visit[:visits] %>, <%= visit[:hits] %>]);
    <% end %>
    new google.visualization.AnnotatedTimeLine(document.getElementById('overall')).draw(data);
    
    
    data = new google.visualization.DataTable();
    data.addColumn('string', 'Month');
    data.addColumn('number', 'Visits'); 
    data.addColumn('number', 'Pageviews');
    var options = {
      hAxis: {title: 'Month'}, 
      vAxis: { baseline: 0 }
    }
    
    <% @monthly_visits.each do |visit| %>
      data.addRow(["<%=t('date.abbr_month_names')[visit[:month].to_i] %> <%= visit[:year] %>", <%= visit[:visits] %>, <%= visit[:hits] %>]);
    <% end %>
    new google.visualization.ColumnChart(document.getElementById('by_month')).draw(data, options);
    
    
    data = new google.visualization.DataTable();
    data.addColumn('string', 'Month');
    data.addColumn('number', 'per visit'); 
    <% @monthly_visits.each do |visit| %>
      data.addRow(["<%=t('date.abbr_month_names')[visit[:month].to_i] %> <%= visit[:year] %>", Math.round(<%= visit[:hits] %> * 100.0 / <%= visit[:visits] %>)/100]);
    <% end %>
    new google.visualization.ColumnChart(document.getElementById('pageviews_per_visit')).draw(data, options);
    
    data = new google.visualization.DataTable();
    data.addColumn('string', 'Month');
    data.addColumn('number', 'duration [s]'); 
    <% @visit_duration.each do |visit| %>
      data.addRow(["<%=t('date.abbr_month_names')[visit[:month].to_i] %> <%= visit[:year] %>", <%= visit[:duration].to_i %>]);
    <% end %>
    new google.visualization.ColumnChart(document.getElementById('visit_dutration')).draw(data, options);
  }
</script>

app/views/accounts/_by_language.html.erb
<h2>Visits by language</h2>
<div class="visualization" id='visualization'></div>

<script type='text/javascript'>
  google.load('visualization', '1', { packages:['corechart']});
  google.setOnLoadCallback(drawVisualization);

  function drawVisualization() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'language');
    data.addColumn('number', 'visits'); 
    <% @visits.each do |visit| %>
      data.addRow(['<%= visit[:language] %>', <%= visit[:visits] %>]);
    <% end %>

    new google.visualization.PieChart(document.getElementById('visualization')).draw(data);
  }
</script>

app/views/accounts/_by_major_flash_version.html.erb
<h2>Visits by flash version</h2>
<div class="visualization" id='visualization'></div>

<script type='text/javascript'>
  google.load('visualization', '1', { packages:['corechart']});
  google.setOnLoadCallback(drawVisualization);

  function drawVisualization() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'flash version');
    data.addColumn('number', 'visits'); 
    <% @visits.each do |visit| %>
      data.addRow(['Flash v<%= visit[:major_flash_version] %>', <%= visit[:visits] %>]);
    <% end %>

    new google.visualization.PieChart(document.getElementById('visualization')).draw(data);
  }
</script>

app/views/accounts/_by_os.html.erb
<h2>Visits by operating system</h2>
<div class="visualization" id='visualization'></div>

<script type='text/javascript'>
  google.load('visualization', '1', { packages:['corechart']});
  google.setOnLoadCallback(drawVisualization);

  function drawVisualization() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'OS');
    data.addColumn('number', 'visits'); 
    <% @visits.each do |visit| %>
      data.addRow(['<%= visit[:os] %>', <%= visit[:visits] %>]);
    <% end %>

    new google.visualization.PieChart(document.getElementById('visualization')).draw(data);
  }
</script>

app/views/accounts/_by_page.html.erb
<h2>Entry and exit pages</h2>

<h3>Top 5 entry pages</h3>
<div class="visualization" id='entry_pages'></div>

<h3>Top 5 exit pages</h3>
<div class="visualization" id='exit_pages'></div>

<script type='text/javascript'>
  google.load('visualization', '1', {'packages':['corechart']});
  google.setOnLoadCallback(drawVisualization);

  function drawVisualization() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Page Title');
    data.addColumn('number', 'Count'); 
    <% @entry_visits.each do |visit| %>
      data.addRow(['<%= visit.entry_page.title %>', <%= visit[:visits] %>]);
    <% end %>
    var options = {
      legend: 'none',
      hAxis: { title: 'page title' }, 
      vAxis: { title: 'pageviews', baseline: 0 }
    }
    new google.visualization.ColumnChart(document.getElementById('entry_pages')).draw(data, options);
    
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Page Title');
    data.addColumn('number', 'Count'); 
    <% @exit_visits.each do |visit| %>
      data.addRow(['<%= visit.exit_page.title %>', <%= visit[:visits] %>]);
    <% end %>
    new google.visualization.ColumnChart(document.getElementById('exit_pages')).draw(data, options);
  }
</script>

app/views/accounts/_by_screen_resolution.html.erb
<h2>Visits by screen resolution</h2>
<div class="visualization" id='visualization'></div>

<script type='text/javascript'>
  google.load('visualization', '1', { packages:['corechart']});
  google.setOnLoadCallback(drawVisualization);

  function drawVisualization() {
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'screen resolution');
    data.addColumn('number', 'visits'); 
    <% @visits.each do |visit| %>
      data.addRow(['<%= visit[:screen_resolution] %>', <%= visit[:visits] %>]);
    <% end %>

    new google.visualization.PieChart(document.getElementById('visualization')).draw(data);
  }
</script>

app/views/accounts/_form.html.erb
<%= render '/shared/errors', :target => @account %>

<%= simple_form_for @account do |f| %>
  <h2>General Information</h2>
  <%= f.input :name %>
  <%= f.input :domain %>
  
  <h2>Contact Information</h2>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  
  <% if @account.new_record? %>
  <h2>User Agreement</h2>
  <div class="eula">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam malesuada velit pulvinar eros accumsan ultrices. Curabitur nisi dolor, laoreet in vehicula eu, rhoncus vitae leo. Nulla adipiscing elit mauris, at ullamcorper orci. Phasellus euismod sagittis odio, ac ultricies tortor vestibulum ullamcorper. Aenean id erat eros. Donec ornare egestas sapien vitae molestie. Vivamus id eros et nisi ullamcorper accumsan. Pellentesque sit amet felis metus. Nulla ullamcorper urna id tortor rhoncus a blandit sem adipiscing. In tempus aliquam tellus a lacinia. Morbi magna purus, dignissim sed pulvinar sit amet, suscipit quis nulla.</p>
    <p>Morbi auctor faucibus augue, at sollicitudin dolor hendrerit et. Proin condimentum, sapien vel auctor consequat, magna nisl convallis libero, eu semper turpis ante in ligula. Donec ligula massa, fermentum vitae mattis laoreet, fermentum vel nibh. Praesent risus ipsum, porttitor tincidunt viverra vitae, rutrum nec massa. Ut quis massa ligula. Donec in elit id odio tincidunt ullamcorper id sed urna. Aliquam velit erat, fermentum et pellentesque eu, aliquet euismod est. Maecenas tincidunt tortor sed lacus egestas fermentum ultrices tellus tincidunt. Pellentesque ullamcorper sodales consectetur. Fusce non nulla quis turpis sodales commodo. Curabitur vel tellus urna, eget luctus turpis. Aliquam erat volutpat.</p>
    <p>Phasellus viverra congue neque eget lobortis. Etiam metus diam, blandit eu tempus ut, tempor vel erat. Sed lacinia vestibulum eros a varius. Maecenas viverra quam at lectus tincidunt tempus. Mauris commodo justo quis purus ultricies ultricies. Nulla fringilla metus vitae lacus tincidunt imperdiet. Nunc ac est mi, in volutpat libero. Nunc mattis nisi a massa aliquet lacinia vehicula purus blandit. Aliquam at mauris augue. Ut eu urna urna.</p>
    <p>Aenean aliquam posuere eros vitae eleifend. Sed gravida velit eu urna ultrices tincidunt rutrum nulla lacinia. Maecenas fermentum vehicula nisi eget pretium. Nullam dui mauris, malesuada at sollicitudin non, scelerisque quis augue. Nunc sodales pharetra lorem, id egestas ante elementum nec. Nam sed risus orci. Aliquam velit augue, mattis in suscipit vestibulum, fringilla et libero. Suspendisse vel risus augue. Sed vel nulla mi, a hendrerit quam. Vivamus mi augue, consectetur at vehicula malesuada, pharetra laoreet dolor. Aenean sollicitudin malesuada augue nec eleifend. Sed a ante at tortor scelerisque ullamcorper faucibus at augue. Etiam interdum lorem at lectus malesuada et semper massa varius. Nam ut dictum mi. Etiam iaculis elit vitae massa venenatis sed iaculis tortor porttitor. Curabitur et nisi diam, ut aliquam tortor. Curabitur volutpat luctus augue vitae tempus. Proin consequat tortor nec arcu ultricies ac pharetra diam facilisis. Curabitur porta consectetur iaculis. Pellentesque ac dui ipsum.</p>
    <p>Pellentesque urna arcu, sollicitudin in porttitor ac, egestas in diam. Duis euismod gravida dignissim. Sed nec ullamcorper nulla. In hac habitasse platea dictumst. Duis tincidunt nunc quis quam faucibus feugiat. Proin ut dui vel lacus porttitor euismod. Duis adipiscing turpis sit amet est tempus vehicula. Aliquam leo orci, semper et gravida vel, placerat a neque. Donec lectus tellus, pellentesque sed condimentum id, feugiat at nunc. Sed eleifend blandit pulvinar. Morbi rutrum nisl sed ante porttitor tincidunt ultrices tortor euismod.</p>
  </div>
  <% end %>
  
  <%= f.submit (@account.new_record? ? 'Agree and continue' : 'Update information'), :disable_with => 'please wait', :class => 'button' %>
<% end %>

app/views/accounts/edit.html.erb
<% stylesheet 'accounts' %>
<% title "Edit #{@account.name}" %>
<%= render :partial => 'form' %>

<h2>Delete account</h2>
<p>You won't be able to access your reports if you decide to do this.</p>
<p><%= link_to 'delete this account', account_path(@account), :method => 'delete', :confirm => "Are you sure you want to permanently delete this account?\nThis action is undoable!" %></p>

app/views/accounts/index.html.erb
<% stylesheet 'accounts' %>
<% title 'Accounts' %>

<% if @accounts.empty? %>
  <p>You currently have no accounts set.</p>
<% else %>
  <table class="classic accounts">
    <thead>
      <tr>
        <th class="name">Name</th>
        <th class="visits">Visits</th>
        <th class="pageviews">Page views</th>
        <th class="per_visit">per visit</th>
        <th class="avg_time">avg. visit</th>
        <th class="actions">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @accounts.each do |account| %>
      <tr id="<%= dom_id(account) %>">
        <td class="name"><%= account.visits.count.zero? ? account.name : link_to(account.name, account_path(account)) %></td>
        <td class="visits"><%= account.visits.count %></td>
        <td class="pageviews"><%= account.visits.sum(:pageviews_count) %></td>
        <td class="per_visit"><%= '%.2f' % (account.visits.sum(:pageviews_count).to_f / account.visits.count) %></td>
        <td class="avg_time"><%=seconds_to_time account.visits.average("TIME_TO_SEC(TIMEDIFF(updated_at, created_at))").to_i %></td>
        <td class="actions">
          <%=link_to 'edit', edit_account_path(account) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%=link_to 'setup new account', new_account_path, :class=>'button new_account' %>

app/views/accounts/new.html.erb
<% stylesheet 'accounts' %>
<% title 'Account Setup' %>
<%= render :partial => 'form' %>

app/views/accounts/show.html.erb
<% stylesheet 'accounts' %>
<% title "#{@account.name}" %>

<div class='range_selector'>
  <%= form_tag account_url(@account), :method => 'get' do %>
    date range: 
    <%= hidden_field_tag :by, params[:by] %>
    <%= text_field_tag :range, params[:range], :id => 'range', :autocomplete => 'off' %>
    <%= submit_tag 'apply' %>
    <%= submit_tag 'reset', :onclick => "$('#range').val('');" %>
  <% end %>
  <span class="showing">
    showing data from <strong><%=l @start_date, :format => :long %></strong> to <strong><%=l @end_date, :format => :long %></strong>
  </span>
</div>

<div id="dashboard" class="clearfix">
  <nav>
    <ul>
      <%= dashboard_menu_item @account, 'summary', nil %>
      <%= dashboard_menu_item @account, 'entry and exit pages', 'page' %>
      <%= dashboard_menu_item @account, 'browsers', 'browser' %>
      <%= dashboard_menu_item @account, 'operating systems', 'os' %>
      <%= dashboard_menu_item @account, 'screen resolutions', 'screen_resolution' %>
      <%= dashboard_menu_item @account, 'flash versions', 'major_flash_version' %>
      <%= dashboard_menu_item @account, 'countries', 'country_id' %>
      <%= dashboard_menu_item @account, 'languages', 'language' %>
      <li class="export">
        <%= link_to 'export data [csv]', export_account_path(@account, :format => :csv), :target => 'blank' %>
      </li>
    </ul>
  </nav>
  <div class='content <%= @partial %>'>
    <%= render :partial => @partial %>
  </div>
</div>

<p>back to <%=link_to 'account list', accounts_path %></p>

<script type="text/javascript">
  $(function(){ $('#range').DatePicker({
    date: ['2009-12-28','2010-01-23'],
    calendars: 3,
    mode: 'range',
    onBeforeShow: function(){
      var val;
      if(val = $('#range').val()) { 
        $('#range').DatePickerSetDate(val.split(","), true);
      }
    },
    onChange: function(formated, dates){
      $('#range').val(formated);
    }
  }); });
</script>

app/views/accounts/show_code.html.erb
<% stylesheet 'accounts' %>
<% title "Code snippet #{@account.name}" %>

<p>Copy the following code, then paste it onto every page you want to track immediately before the closing &lt;/head&gt; tag</p>
<% content_tag :textarea, :rows => 12, :class=>'snippet', :readonly => true do %>
<script type="text/javascript">
 var _zys = { id: "<%= @account.code %>" };
 (function(d, t) {
  var g = d.createElement(t),
      s = d.getElementsByTagName(t)[0];
  g.async = true;
  g.src = ('https:' == location.protocol ? 'https://' : 'http://') + '<%= HOST_NAME %><%= zys_path %>';
  s.parentNode.insertBefore(g, s);
 })(document, 'script');
</script>
<% end %>

<p>back to <%=link_to 'account list', accounts_path %></p>